# Generated by Django 3.0.7 on 2020-09-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
    ]
