# Generated by Django 3.0.7 on 2020-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailAddress',
            field=models.EmailField(max_length=100),
        ),
    ]
