# Generated by Django 3.0.7 on 2020-09-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Organizations', '0013_auto_20200901_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfAppointment', models.DateField()),
                ('timeOfAppointment', models.TimeField()),
                ('reasonOfAppointment', models.CharField(blank=True, max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(blank=True, max_length=200)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('lastUpdatedBy', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Organizations.Organization')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Appointments.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.User')),
            ],
        ),
    ]
