# Generated by Django 3.0.7 on 2020-09-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_from', models.TimeField(blank=True)),
                ('monday_to', models.TimeField(blank=True)),
                ('tueday_from', models.TimeField(blank=True)),
                ('tueday_to', models.TimeField(blank=True)),
                ('wednesday_from', models.TimeField(blank=True)),
                ('wednesday_to', models.TimeField(blank=True)),
                ('thursday_from', models.TimeField(blank=True)),
                ('thursday_to', models.TimeField(blank=True)),
                ('friday_from', models.TimeField(blank=True)),
                ('friday_to', models.TimeField(blank=True)),
                ('saturday_from', models.TimeField(blank=True)),
                ('saturday_to', models.TimeField(blank=True)),
                ('sunday_from', models.TimeField(blank=True)),
                ('sunday_to', models.TimeField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(blank=True, max_length=200)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('createdTime', models.TimeField(auto_now_add=True)),
                ('updatedBy', models.CharField(blank=True, max_length=200)),
                ('updatedDate', models.DateField(auto_now=True)),
                ('updatedTime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('phno1', models.CharField(max_length=10, unique=True)),
                ('phno2', models.CharField(blank=True, max_length=10, unique=True)),
                ('phno3', models.CharField(blank=True, max_length=10, unique=True)),
                ('emailAddress', models.EmailField(max_length=100, unique=True)),
                ('photo1', models.ImageField(blank=True, upload_to='photos/organization/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/organization/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/organization/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/organization/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/organization/')),
                ('websiteLink', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(blank=True, max_length=200)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('lastUpdatedBy', models.CharField(blank=True, max_length=200)),
                ('organizationType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Organizations.Org_Type')),
            ],
        ),
    ]
