# Generated by Django 3.0.7 on 2020-09-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='createdTime',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='updatedTime',
        ),
    ]
