# Generated by Django 3.0.7 on 2020-09-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_auto_20200901_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='updatedBy',
        ),
    ]
