# Generated by Django 3.0.7 on 2020-09-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_auto_20200901_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
