# Generated by Django 3.0.7 on 2020-09-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0007_organization_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='availability',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
