# Generated by Django 3.0.7 on 2020-09-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0011_auto_20200901_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='friday_from',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='friday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='monday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='saturday_from',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='saturday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='sunday_from',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='sunday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='thursday_from',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='thursday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tueday_from',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tueday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='wednesday_from',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='wednesday_to',
            field=models.TimeField(blank=True, default='20:00'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='websiteLink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
