# Generated by Django 3.0.7 on 2020-09-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0012_auto_20200901_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
